<?xml version="1.0"?>
<robot xmlns:xacro= "http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find fishbot_description)/urdf/robot/common_inertial.xacro"/>
    <xacro:macro name="base_xacro" params="length radius">
        <!--虚拟部件 -->
        <link name="base_footprint"/>

    
        <!--机器人的身体部分  -->
        <link name="base_link">
            <!-- 部件的外观描述  -->
            <visual>
                <!-- 沿着自己几何中心的偏移和旋转 -->
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <!-- 部件的外观形状 -->
                <geometry>
                <!-- 圆柱体半径和高度 -->
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <!-- 部件的外观材质 -->
                <material name="blue">
                    <color rgba="0.0 0.0 1.0 1.0"/>
                </material>
            </visual>
            <!-- 添加碰撞属性 -->
            <collision>  
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${radius}" h="${length}"/>

        </link>

        <joint name="base_joint" type="fixed">
            <origin xyz="0.0 0.0 ${length/2.0+0.032-0.001}" rpy="0.0 0.0 0.0"/>
            <parent link="base_footprint"/>
            <child link="base_link"/>
        </joint>
    </xacro:macro>
 
</robot>

